# NeoForge Mod 元数据配置
# 鞘翅增强模组 - NoFireWorkFly

modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Fuxingcheng"
logoFile="logo.png"
description='''
This mod enhances the elytra flight experience by removing the need for fireworks. You can launch into the air and sustain flight entirely without consuming any firework rockets.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="caelus"
    type="required"
    versionRange="[7.0,)"
    ordering="NONE"
    side="BOTH"
